apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-issuer
spec:
  acme:
    server: https://ca.k3sdemo.example.org/acme/acme/directory
    email: user@example.org
    privateKeySecretRef:
      name: step-ca-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx
